### ISSUE TITLE
Installation: Raspbian on Pi zero with wifi

### ISSUE THREAD

**Issue by tixxdz** [opendevices/iot.apps#4]
@nwd0 we should plan to add Raspberry Pi Zero doc, so start by copying same doc and we update later.

**Comment by nwd0** [comment]
Add documentation first version, of How to install raspbian on Raspberry Pi Zero W for Windows users.
[Raspbian on Raspberry Pi Zero W](https://github.com/opendevices/iot.apps/blob/master/doc/od-iot-raspbian-rpi-zero-windows.md)
and also add the French translation  
[Raspbian on Raspberry Pi Zero W](https://github.com/opendevices/iot.apps/blob/master/doc/od-iot-raspbian-rpi-zero-windows-fr.md)
Will improve it more and add wifi config
